### PR TITLE
Allow specification of extra kwargs to Runner.

### PR DESCRIPTION
**Pull request by weykent**
This means that tests can do things like run modules in check mode or request a diff. It's useful in some tests I've written.

### CODE REVIEW

**Comment by weykent** [comment]
It seems like travis and coverage are both broken on master too. I could make a separate PR for fixing those, if you'd like.

**Comment by jlaska** [comment]
@weykent I have code not yet pushed for handling the new ansible-2.0.0 library.  We can track that portion elsewhere.

**Comment by jlaska** [comment]
@weykent thanks for taking the time to construct this PR.  I like the concept, but have some suggestions.  Rather than supporting `_runner_kwargs` as a module parameter, I'd prefer using the existing pattern for passing data from `py.test` user to the `Runner` object.  For that, the code offers command-line options, and a marker for altering ansible parameters on a per-test basis.  My suggestion would be to ...

1. Add a command-line option `--ansible--check` to enable it session wide
2. Also, use the existing `pytest.mark.ansible()` for allowing function-scope override for `check=True`

I do like the idea of overriding ansible parameters, but not through the module directly.  We could expose a method/attr on the `ansible_module` object itself (e.g. `ansible_module.__options.check=True` .  But that could be a subsequent PR.

**Comment by weykent** [comment]
I'm not entirely sure I agree about how to specify `check=True`. Making it a command-line option doesn't make a lot of sense, because as far as I understand it, tests written with `pytest-ansible` will expect that the module successfully ran if you call `ansible_module.whatever` and it indicates success. That is, tests will then verify that whatever the module was supposed to do actually happened. If `--ansible-check` was globally specified, then none of those calls would do anything anymore, and all the tests would fail.

You can see the tests I've been writing here: https://github.com/weykent/ansible-runit-sv/blob/205add8261bb7cabc5bd8f6942727e2adca2a9b5/tests/test_runit_sv.py

In my own tests, most of the tests ensure that if the module succeeded, then its effects are visible. There's another test to ensure that if check mode is specified, then the effects are *not* visible. I hope this makes it more clear the level of granularity I'm reaching for here, and why.

What I have so far could use the `pytest.mark.ansible` to indicate `check=True`, as I only call the module once per test. I was trying to imagine in what circumstance one might want to call a module in both check and not-check modes, and couldn't come up with anything, but I don't think that is to say nobody would need it.

So, I'm definitely not strongly attached the the interface I proposed in this PR (and I'd be willing to change it), but I'm not sure I agree with the interface proposed aove.

**Comment by jlaska** [comment]
@weykent Thanks for your comments.  The intent with the `ansible_module` fixture is that it allows a tester to call a specific module directly.  The arguments to the called method should match exclusively what the ansible module requires.  I feel a bit nervous passing along unused `ansible` module attributes that have special meaning to the `py.test` fixture.  We can head that direction eventually if there is a great need, just don't want to do it in a one-off manner.

> If --ansible-check was globally specified, then none of those calls would do anything anymore, and all the tests would fail.

That is correct.  And I'd likely need to add tests for that.  I attempt to mimic supported `ansible` parameters with the `pytest-ansible` plugin.  While it may make more sense for uses to enable `check=True` mode on a specific test class/function, the pattern I've followed so far allows for the tester to optionally pass the parameter to the `py.test` command-line (much like with `ansible`).

> What I have so far could use the pytest.mark.ansible to indicate check=True, as I only call the module once per test. I was trying to imagine in what circumstance one might want to call a module in both check and not-check modes, and couldn't come up with anything, but I don't think that is to say nobody would need it.

I agree.  While we can create a mechanism for altering `ansible` command-line parameters within a test, the current structure allows one to specify ansible parameters globally (via `py.test` command-line options), or per-test/class (via fixtures).

Thanks again for your feedback!

**Pull request closed without merging**
